### ISSUE TITLE
Tracks not playing on mobile

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ca.epl.capitalcityrecords#103]
Between 2:58 and 3:25 I tried playing randomly selected songs from tuques, Electricity for Everybody and Choir and Marching Band and none of them played. I am able to hear YouTube videos so the sound is working on my phone. 

What happens each time is that when I press play, the playbar appears and the pause button appears, but no music plays. 

I successfully played a song from Electricity for Everybody on my phone around 1:30. Things I noticed then: the download buttons were not yet permanently visible. The download buttons are now permanent. 

Android phone, Lollipop, Chrome 43, btwn 2:58-3:25pm MT, 29 July 2015

**Comment by prestonaustin** [comment]
@mbrakken MMS crash/restart?

(@acecarruthers we've crashed the beta platform 3 or 4 times today, so this
may be nothing but that, but keep reporting these with times. A test worth
running if it happens again is to close page, clear caches, and reload. If
MMS is down, graphics and tracks won't load or play. If you see that,
report that too as it is also possible for other things to cause that in
theory)

**Comment by prestonaustin** [comment]
@acecarruthers I'm moving this to Pending Debug Info to keep it alive but I think it isn't a problem. If any further problems like it contradict that, we should update here and reattach this to Production Ready.

**Comment by mbrakken** [comment]
I'm guessing MMS crash, but I haven't checked times. Given the timezone
difference, these all seem to be when we were down and I was hidden in
other work.

**Comment by acecarruthers** [comment]
OK. The tracks are now playing on my phone after about a 12 second delay. That may be a different problem or it may be my phone's problem. I'll look into it.

**Comment by prestonaustin** [comment]
@jjg @mbrakken this resonates with some reports Marc has on ember-player, so I'm mentioning you both here just FYI if we are looking for cases on that stuff. Unclear if this is common, and unclear if it is ember-side, mms/mtc-side, or in between.

**Comment by mbrakken** [comment]
Just to check, is it the same on wifi vs cell network? My first suspect on slow to play for mobile is network latency / download speed.

**Comment by prestonaustin** [comment]
@acecarruthers @mbrakken Yes I'm assuming this is either delayed back and
forth to establish the playable track's load, or a slowed down response or
slow-starting load on the MMS hit from the client side. We may want to add
some profiling code on the client that logs when it is trying to request
things vs when it starts processing the replies, and when it gets data
events.

**Comment by kellyhiser** [comment]
lots of code changes since this report, closing.
