### ISSUE TITLE
Remove dependencies depreciated servers

### ISSUE THREAD

**Issue by jjg** [therabble/ca.epl.capitalcityrecords#115]
The servers behind the hostnames below are in the process of being decommissioned.  Let's make sure any references to these hosts in this (or any other CCR application) are updated and/or removed and update this issue when it has been confirmed that there are no dependencies on these hosts:
- jsfs.capitalcityrecords.ca
- ccrjsfs.murfie.com
- ccrapi.murfie.com
- jsfs.murfie.com
- jsfs-dev.murfie.com

**Comment by mbrakken** [comment]
@jjg The only one of these I saw any reference to are https://ccrapi.murfie.com and https://ccrjsfs.murfie.com. I don't see any code that actually calls them, though.

I checked the JSON for published artist / album / poster assets, and all media urls point to ccrapi2.murfie.com.

I believe there are no outstanding dependencies on anything you list.
