### ISSUE TITLE
Album not streaming all the way through

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ca.epl.capitalcityrecords#123]
Choir and Marching Band is having some trouble streaming https://capitalcityrecords.ca/albums/choir-and-marching-band-life-found-on-superhot-body-only-one-light-year-away 

User pressed play on the first track. When the song ended the next track didn't start. User pressed play on the album cover and skipped forward in the playbar to track 2. Track 2 moved seamlessly into track 3. At the end of track 3 streaming stopped again. User waited a full minute before pressing play on track 4. During track 4, playback cut out twice - just for a second or so - and then continued. Track 5 did not start at the end of track 4. Here's a screenshot from when track 3 stopped:

![playbackerr](https://cloud.githubusercontent.com/assets/7355887/9294384/ef1d44d0-4408-11e5-9d8d-776ed7c462d0.png)

I have tested a few other albums (Nature Of, Sirch.) but they don't appear to be having the same trouble so far. 

(Desktop, Windows 7, Chrome 44, 10:40am, 16 Aug, 2015, internet connection is wired)

**Comment by acecarruthers** [comment]
Update: track 7 of Nature Of ended and Track 8 did not start. Track 7 also experienced a weird sound cut out about half way through. https://capitalcityrecords.ca/albums/nature-of-nature-of 

All the details above are the same, except the time was 11:38am MT

**Comment by prestonaustin** [comment]
@acecarruthers are the effects reproducible on subsequent playthrough?
(i.e. same error at the same place)

@jjg can you see any log footprints that might shed some light on this?
These should (I think) be serving from MMS cache so it may be interesting
to grab its contents for these tracks before any restart or cache flush
happens.

**Comment by acecarruthers** [comment]
@prestonaustin Yes, I tested track 3 of Choir and Marching Band twice with the same result.

**Comment by jjg** [comment]
Audio is not cached ATM @prestonaustin, only images.

**Comment by acecarruthers** [comment]
I retested Nature Of and the 8th track did start right after the 7th - but now it has stopped at the end of the 9th track.

**Comment by prestonaustin** [comment]
@acecarruthers How are other albums doing? Clearly we should determine how
prevalent problems are, if we found 1 in testing 2 other albums it may be a
lot. I'm on phone with limited battery until I get home, so preserving that
for keeping in touch, but not a super useful tester for a couple hours here.

@jjg if you want jlog client side playback logging additions can you make
an ask to @nagapampa and/or @mbrakken to see if and when either may be able
to add and deploy what you need?

**Comment by acecarruthers** [comment]
@prestonaustin I made it all the way through Kaz Mega and the Velveteins without the tracks stopping. There was another strange pause in Track 2 of the Velveteins.

**Comment by mbrakken** [comment]
Is all of this testing on Chrome desktop? Does Firefox play fine? If both are true, this sounds related to https://github.com/murfie/mms/issues/34 (`net::ERR_CONTENT_LENGTH_MISMATCH`, related to how Chrome fetches media). If `net::ERR_CONTENT_LENGTH_MISMATCH` occurs in the last second or so of the track, the browser can be slow to recover and/or fail to recover (the failure might be timeout related). The stutters during playback are instances of the error where the browser does recover and re-fetch the media.

That issue is under active investigation and I *believe* close to resolution. It got pushed back in favor of unblocking 10xi, but is queued up once ingest is happening.

**Comment by acecarruthers** [comment]
@mbrakken Previously all testing has been on Chrome desktop. I went to test track 3 of Choir and Marching Band on Firefox 40 Desktop and the track just stopped halfway through. After about 2 minutes I gave up on it starting again. I pressed pause and then play again and it didn't start. 

I tried starting the tracks before and after and then I returned to track 3 - it was still stuck mid song and wouldn't restart. 

![2015-08-17playbackstopped](https://cloud.githubusercontent.com/assets/7355887/9308440/60f2d2b0-44c1-11e5-9e32-f625ccd052a7.png)

It is also perhaps worth noting that both track 2 and track 4 took around 7 seconds before they started playing. 

Alex, Firefox 40, Windows 7, 17 Aug, 2015, ~9:20am MT https://capitalcityrecords.ca/albums/choir-and-marching-band-life-found-on-superhot-body-only-one-light-year-away

**Comment by acecarruthers** [comment]
I just tested Nature Of on Firefox 40 and had 0 problems streaming all the way through. Perhaps there are a couple different little issues at work here?

**Comment by prestonaustin** [comment]
So it would appear. I'm a little stumped atm but we'll keep looking at it.

**Comment by jjg** [comment]
Did we get confirmation whether or not `ERR_CONTENT_LENGTH_MISMATCH` is thrown when the playback error occurs?

**Comment by prestonaustin** [comment]
@jjg @mbrakken we would expect that error only in chrome, correct? Can you
paste instructions here so Alex and I can both test.

**Comment by mbrakken** [comment]
@jjg I did see `ERR_CONTENT_LENGTH_MISMATCH` thrown yesterday when I
briefly tested, but I looked for one occurrence and then moved on to other
things.

@prestonaustin and @acecarruthers: to test, open up chrome's developer
console. To get the via menus on a Mac, go to View --> Developer -->
JavaScript Console. On a Windows or Mac machine, you can also click on the
little hamburger menu to the right of the location bar (where you enter
urls), then More Tools --> JavaScript console.

The hot keys option is Option+Command+J on a Mac or Ctrl+Shift+J on Windows.

When streaming, if an interruption occurs you'll probably see the error
message in red. In our testing, the cutout tends to occur about 3:20 into a
song, give or take (@jjg could probably tell you how many bits are
downloaded when it happens).

**Comment by acecarruthers** [comment]
Playing Track 1 of Choir and Marching Band in Chrome and I am getting repeating `ERR_CONTENT_LENGTH_MISMATCH` messages. First one when the song momentarily cut out and then again 10 or so seconds after the song ended and then they keep appearing about 2 minutes apart. Track 2 is not starting. 

![2015-08-17 10_31_01-life found on](https://cloud.githubusercontent.com/assets/7355887/9310275/13798dfc-44cc-11e5-8742-f21310528d1a.png)

**Comment by mbrakken** [comment]
@acecarruthers Does the second of these errors occur right near the end of
the track? If so, that correlates with other examples I've seen that break
transitions to the next track (
https://github.com/murfie/ember-player/issues/30)

**Comment by jjg** [comment]
I think @mbrakken is correct that this is related to https://github.com/murfie/mms/issues/34 and will likely be resolved once that issue has been fixed.

**Comment by acecarruthers** [comment]
@mbrakken The second error occurred a few seconds after the track ended.

**Comment by acecarruthers** [comment]
Are there any updates on this @mbrakken? I just tried listening to Choir and Marching Band track 1 in Chrome and the track stopped at the end and wouldn't move forward to track 2. However, I had the JS console open and there was no ERR_CONTENT_LENGTH_MISMATCH

**Comment by acecarruthers** [comment]
Actually, after about 5 minutes an error appeared: 
Failed to load resource: net: :+1: ERR_CONTENT_LENGTH_MISMATCH

**Comment by mbrakken** [comment]
Sorry, I haven't thought about this in ages. I'll try to take a look soon.
I feel like we successfully addressed this on Murfie, but I'll need to
review some history.

**Comment by kellyhiser** [comment]
I just experienced the problem Alex described above: track 1 plays, but stops about 5 minutes in and doesn't advance. The rest of the tracks at least start (haven't listened the whole way through). Firefox. JS console reads: "no element found"

**Comment by kellyhiser** [comment]
This is still happening. I'm not sure of the status of murfie/mms#34 that @jjg mentions may fix this, as the link is a dead end (at least for me).

**Comment by kellyhiser** [comment]
this works now.
