### ISSUE TITLE
Collection data for jury

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ca.epl.capitalcityrecords#127]
In order for the jury to make informed decisions about how to grow a diverse collection, I am going to put together a report for them on the voluntary demographic information and genre information we collected. Please email me a CSV file with the following fields for each artist. 
Gender
Ethnicity
Tags
Genre

**Comment by mbrakken** [comment]
@acecarruthers is this no longer a target? I was looking to incorporate it
somehow, but had done no work on it yet.

**Comment by acecarruthers** [comment]
Oh oops, it is a target, I meant to move it from the Milestone because it isn't an immediate priority not close it. I was able to spend a half hour and collect the data just by looking through the artist submissions. .

**Comment by kellyhiser** [comment]
in progress see https://github.com/therabble/musicat-stem/issues/82
