### ISSUE TITLE
Data/metadata export for dark archive test

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ca.epl.capitalcityrecords#130]
The long-term goal is to be able to automate the export of data and metadata from the Rabble server into the U Alberta Libraries' dark archive. The first step towards setting this up is for us to send them a test export to give them a sense of what objects and what data they should prepare for. 
They have requested just a small amount of content for the test. 

I think the test should include the following 2 albums and 2 posters as well as all the associated metadata:
- The Velveteins, Fresh Claws https://capitalcityrecords.ca/albums/the-velveteins-fresh-claws
- Tyler Butler, Violence https://capitalcityrecords.ca/albums/tyler-butler-violence
- Ross Campbell poster RCampbell0007.jpg https://capitalcityrecords.ca/posters/89a50b4491ee22e893eacfe9fbf55c382051762c-2015-07-16t15-55-57-237z-rcampbell0007-jpg
-  Voice Industrie poster Mosh Fest 92.jpg https://capitalcityrecords.ca/posters/f97ab32174138d06e99422773d8592aee9216b22-2015-08-26t21-21-46-487z-mosh-fest-92-jpg

They haven't requested the metadata data in any particular file format so that is your discretion. They would appreciate any documentation you can provide regarding
- file naming conventions
- how data is associated with metadata
- checksums

I think the best way to send them the test is by putting the data and metadata in a Google Drive folder that we can share with them. Let me know if you have a different suggestion or preference.

**Comment by kellyhiser** [comment]
closing as we're directly in touch with U of A archive folks now
