### ISSUE TITLE
Questions re: Dark Archive export

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ca.epl.capitalcityrecords#131]
1) What is the best way to move the data/metadata without having to download it to a hard drive and drop it off at the University in person. Could the CCR API be adapted for this purpose? What do you need to know from me/the University to be able to answer this question?

2) The University has requested we provide them with a storage estimate. I was wondering if you could tell me how much we’re storing now and how much of it is audio vs. image?

**Comment by acecarruthers** [comment]
tied to #130

**Comment by pschoenberg** [comment]
This is only a test.

**Comment by kellyhiser** [comment]
closing as we're directly in touch with U of A archive folks now
