### ISSUE TITLE
Reports interface

### ISSUE THREAD

**Issue by mbrakken** [therabble/ca.epl.capitalcityrecords#138]
We should add a reports interface and endpoint so that site operators / admins can define and and run reports dynamically. 

This interface should be restricted to admins and those with the appropriate access to a "reports" stage.

The interface should present the operator with the types of data available to build reports off of, and provide a way to select data sources, attributes to be included, and provide arbitrary labels for those attributes. We will persist these report schemas so they can be trivially retrieved and presented to an operator in the future Persisted report structures should be alterable in the future.

The reports interface should present reports that have been defined and allow for download of structured data.

Running a report would then entail selecting a defined report, declaring a date range, and then clicking a download button. (NB: I'm thinking of different UIs / UXs for this, but we can run with this flow for now).

Nice but not required is Preview capability, so that an operator can confirm within the application that the downloaded data is appropriately structured.

Note: all reporting will be run in the client. The server is just for holding report definitions / schemas. All report definitions should be retrievable from a single API call to `/reports/`.

**Comment by prestonaustin** [comment]
@mbrakken are you envisioning implementing _both_ log/timeseries _and_
content/structure reporting happening here?

For example, are "MARC export of Albums" or "Manifest in CSV of all
published objects" in scope here as well as "Number of items streamed last
month"?


-- 
Preston Austin - @gl33p

**Comment by mbrakken** [comment]
I think both could happen. I don't see why not, but maybe there's something
about some of the reports (MARC, for instance) that I'm unaware of.

I assume time-series data would be based on what we formally log to jlog.
Content reporting would be based on content that populates the site. It
should be easy to separate types of reports via data sources.

**Comment by prestonaustin** [comment]
I definitely think it could reach into all data that have schema and APIs
to query. The level of programmatic processing on the retrieved result that
can be done without a coding toolkit will be constrained by making it safe.
I would restrict it to declarative n:n field mappings and a programmer
defined set of encoding transforms, filtering, and record counting options.
Happy to help spec.

**Comment by kellyhiser** [comment]
see https://github.com/therabble/musicat-stem/issues/82
