### ISSUE TITLE
Reporting Requirements - Oct and going forward

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ca.epl.capitalcityrecords#139]
The document below gives a summary of the reports we need to send to SOCAN and CSI this month and then going forward. It also describes our data storage needs. The information is incomplete, but it is the best that I know at the moment.
https://drive.google.com/open?id=1u2a9GDKWqm7xUXElDB-sCX9MJByfkM014lsQ9SFPCjs 

I just now received feedback from SOCAN on the test reports we sent them in August. They have asked us to make the following small changes to the Monthly Sales Report:
1. fields 29 and 31 should be left blank. (They currently are being reported as "PD".)
2. Field 32, "Month Played", should follow the format YYYYMM

**Comment by prestonaustin** [comment]
this is an admirably terse issue spec :D

**Comment by acecarruthers** [comment]
oops! @prestonaustin I've added a few more details.

**Comment by pschoenberg** [comment]
Just checking in on this one.   SOCAN is asking revised reports by October 20.   

Will we be getting the revised reports in time?    This one seems to be extremely time crunched.

**Comment by mbrakken** [comment]
Hi @pschoenberg. Sorry for radio silence. I have full confidence we'll be able to get reports to you or you'll be able to access them yourselves before the 20th.

**Comment by pschoenberg** [comment]
Has there been progress in the last four days?

**Comment by prestonaustin** [comment]
Carie already has reporting code done, and Marc is working on deploying a
basic admin auth and UX so you can access them directly at an appropriate
path - plan was to deploy today. I'll confirm that we are on track or we
can opt to run this report for you. Will update around 2:00c here.

**Comment by mbrakken** [comment]
Hi @pschoenberg and @acecarruthers 

This url is now live: https://capitalcityrecords.ca/admin/reports

You will be prompted to login using the email address & password used on submissions.capitalcityrecords.ca, eg for http://submissions.capitalcityrecords.ca/review-and-publish/submissions

I know @acecarruthers has working credentials for all that. I'm not sure if @pschoenberg has his own. 

I am working on an interface for current admins to grant admin access to other people, but that doesn't exist yet. If you need access and don't have it, please let me know and I can get you access manually.

The interface is an early stub for general admin tasks, with the eventual goal of folding everything for the publishing process into it.

Let me know if you have questions, or if there's anything missing from the SOCAN / CSI reports (all under the SOCAN heading). The honorarium reports & data exports do not current work on this interface.

**Comment by pschoenberg** [comment]
Thanks for the update @mbrakken

I do not have an Admin login for CCR.
Please set one up for me.

**Comment by mbrakken** [comment]
@pschoenberg I just sent you an email with info about signing in as an admin (I didn't want to share credential here :)

Let me know if you have questions.

**Comment by acecarruthers** [comment]
@mbrakken this is fantastic. Thank you! I have sent the reports on to SOCAN and CSI. I have a follow up question and a request:

Question. I created a Streams report and a Users report each covering the time between July 8 and Sept 30. The Streams report shows 12155 streams and the Users report shows 12154 streams. Any idea why there would be a 1 stream difference? (I am using Google Refine to review the data and I have double checked that I am not counting the header row as a stream).  

Request. In the Downloads report, field 2 (Deal Type Code) should be 'DPD' rather than 'download'. Deal Type Codes are on pg. 2 of the retailer reporting file format doc. 

Thanks!

**Comment by mbrakken** [comment]
Excellent. I'd need to compare across the two outputs to get a sense of why they're off by one. Is it immediately obvious what is missing or extra?

A column heading is trivial. I have an open issue to redesign reporting so that it's configurable by an admin rather than hard-coded. I'll make a note in that issue about the heading, since we'll want to preload it with configurations that meet your needs.

Other than those two points, is there anything else needed on this issue or can we be prepared to close it?

**Comment by acecarruthers** [comment]
@mbrakken It isn't immediately obvious what is missing or extra, unfortunately. 

That reporting redesign sounds like a great long term goal. I want to confirm that both the header for field 2 and the content in each row in field 2 should be 'DPD'. 

I am still waiting for CSI to send me their final decision about how they want stream reports. It could be exactly the same as SOCAN, or it could be slightly different. I don't know if it would be best to start a new issue for that when they finally get back to me, or keep all of the details about SOCAN/CSI reporting in one place.

**Comment by acecarruthers** [comment]
I just pulled the reports for October and found the same mysterious error. The stream report listed 1840 total streams and the unique visitor report listed 1839 streams.

**Comment by acecarruthers** [comment]
Here are the two files to compare when you have a chance to get to this:
[EP-188326_stream_20151031_2015112_164915_UVR.txt](https://github.com/therabble/ccr-app/files/25787/EP-188326_stream_20151031_2015112_164915_UVR.txt)

[EP-188326_stream_20151031_2015112_164835.txt](https://github.com/therabble/ccr-app/files/25786/EP-188326_stream_20151031_2015112_164835.txt)

**Comment by mbrakken** [comment]
Ok. I haven't looked into any of this yet, but can try to prioritize it.
@nagapampa, do you have any thoughts on this?

**Comment by acecarruthers** [comment]
@mbrakken @nagapampa Don't worry about prioritizing this before we launch the next Call for Submissions. A single stream costs us $0.0013, so this isn't a huge problem. It would be nice to have figured out at some point, so I'll keep documenting it when it happens.

**Comment by nagapampa** [comment]
@acecarruthers I can take a look at this again
