### ISSUE TITLE
Admin interface for handling users

### ISSUE THREAD

**Issue by mbrakken** [therabble/ca.epl.capitalcityrecords#146]
Use case: allow site admins to setup other existing or new accounts with access to restricted areas. For instance, inviting jurors, pulling in other folk in the library for managing review & publication of content, etc.

We should have an easy way to manage user accounts given a set of publishing stages (jury, invitations, review/publishing, reporting/analytics), and other tasks like granting permissions, opening and closing submission rounds, etc.

Requirements: email address, selected roles / access, options of name and a note that will be included in an email.

Admins should also be able to see current users / roles and make updates.

When someone is granted new access, we should send an email which provides a url to access appropriate sections. We probably will also want to incorporate a password recovery process.

**Comment by kellyhiser** [comment]
see https://github.com/therabble/musicat-stem/issues/23
