### ISSUE TITLE
Banner content management system

### ISSUE THREAD

**Issue by mbrakken** [therabble/ca.epl.capitalcityrecords#160]
Rather than having banner content be a dev concern, we should make it a content-management, admin concern.

Currently the json for banner content is hard coded into the route that uses it. We should make this content a stand alone json file that is loaded in async and can be edited by others.

It should be part of the project file system, but trivial to find and edit by non-devs:

First version can involve reading the raw file out of github directly, ideally out of a "content" folder at the application root.

The app should then load the file directly out of Github as opposed to the file on the app server.

We may want to look at a caching mechanism for this. Yahara has one, although it's not easily portable since the server architecture is different (ie Yahara isn't an ember-cli project).

We should treat this as a prototype of a general static content management system.

**Comment by nagapampa** [comment]
@mbrakken I added the 'content' folder in the master branch so I could reference it in the 'banner_cms' branch.  The code is up to grab the JSON from the file.

![banner_call](https://cloud.githubusercontent.com/assets/2964839/10948856/5bc988b6-82f5-11e5-8f5b-dd4f9a8192a6.png)

In the network tab, the .json file is successfully called but in the code it's returning NULL.  I believe this has to do with how the promise is set up.  I tried to mimic the reporting promise.  All the code is checked into the 'banner_cms' branch if you could take a quick look.

Does anything else need to follow this format for content mgmt?

**Comment by mbrakken** [comment]
If you `console.log(json)` where your promise resolves, what do you get?

Also, I think you'll need to update the JSON you're requesting so that keys and values are all in double quotes. I don't think it's valid JSON otherwise.

You'll probably also need to `JSON.parse(json)`, since it's just text coming across the wire.

**Comment by nagapampa** [comment]
@mbrakken It's showing up as null when I do a console.log

**Comment by mbrakken** [comment]
In your handler, what is `this.response` look like? If that has content, try `return resolve(this.response);`

**Comment by nagapampa** [comment]
@mbrakken I need to learn to be patient I guess.  It was still returning the invalid JSON after I had added the double quotes (good call on that).  I had to wait about 5 minutes and do a hard refresh in Chrome to see the most current results.

So it works just fine.  Everything is still checked in - I didn't have to change any code.  It was just an issue with the JSON.  

I added a little documentation at:
https://github.com/therabble/ccr-app/wiki/Content-Management

Thanks @mbrakken

**Comment by mbrakken** [comment]
Also, in the interest of simplicity (and following conventions used elsewhere in the code), at the top of the file I'd `import ajax from "ic-ajax";`, and then just use `ajax(url).then(function(resp){ // do something });` instead of writing a custom handler.

`ic-ajax` is really just a promisified wrapper around jQuery.ajax(), and while I generally try to avoid jQuery, this is my current exception because of historical need to support `XDomainRequest()` and `ActiveXObject()` for Microsoft browsers.

**Comment by mbrakken** [comment]
Awesome. So, is it possible to actually add image files to the repo directly from github? If not, I think the next step is to add image upload capability inside of an /admin/content/banners path.

**Comment by mbrakken** [comment]
If we are able to add banner images directly in github, those will also need to be loaded directly out of github (since they won't be deployed to the server). If we are serving them from the server, we'll need to disable ember cli's fingerprinting of those files: http://www.ember-cli.com/user-guide/#fingerprinting-and-cdn-urls

**Comment by nagapampa** [comment]
@mbrakken The only way I see that working is using the image path URL from an issue where an image has been uploaded... I don't see a way in the GUI to upload a file... just create one in text.

**Comment by mbrakken** [comment]
OK, so i think we should add in some image upload capability at /admin/content/banners. The next step after that can be a form for editing banner json directly from the app. Github API integration is probably needed for this. I'm not really sure how that works, though.

A non-github approach would be to add an endpoint for storing this content data in redis behind the musicat API. This may be the eventual direction, but I think a Github-based approach could be a good intermediary.

**Comment by prestonaustin** [comment]
Check in at the earlier of 6th of July or 1 week before agreed go-live for submissions.

**Comment by prestonaustin** [comment]
Update: Issues with working around ember's asynch management and a need to normalize approaches to things have @whblondeau and @prestonaustin implementing this as an ember-data model, backed by the MUSICat-API data store. Work that has come before will be deprecated in this update. We may still have to rewrite the banner view components, haven't yet looked into their construction - hoping they can accept data asynchronously already but if not, they gotta go.

**Comment by prestonaustin** [comment]
See also https://github.com/therabble/musicat-api/issues/73

**Comment by kellyhiser** [comment]
see https://github.com/therabble/musicat-stem/issues/22
