### ISSUE TITLE
move poster admin tools from old app

### ISSUE THREAD

**Issue by kellyhiser** [therabble/ca.epl.capitalcityrecords#209]

**Comment by prestonaustin** [comment]
Only tenuously part of milestone, but some work is waiting for submission so asap is good after submissions and publishing fixes for submitting musicians and albums are done.

**Comment by kellyhiser** [comment]
Issue moved to [therabble/musicat-stem #94](https://github.com/therabble/musicat-stem/issues/94) via [**ZenHub**](https://www.zenhub.com/)
