### ISSUE TITLE
add capability to edit images in Review & Publish 

### ISSUE THREAD

**Issue by kellyhiser** [therabble/ca.epl.capitalcityrecords#224]
I click "update image" and the upload button and message appears, but when I drag and drop or select a file, nothing happens (nothing appears in the JavaScript console either). I tested with two images just in case, but neither worked. 

This happened for: https://wax.capitalcityrecords.ca/admin/review-and-publish/submissions/artists/barry-campberll-band

**Comment by mbrakken** [comment]
Yeah. That's not hooked up yet, since I didn't know what type of upstream notification / re-sign / etc process there should be.

It's easy to implement, FWIW. That page is the identical form code for the one artists use, just without all the actions wired up.

**Comment by prestonaustin** [comment]
Overrides are presumed to be authorized out of band or respectful fair use
so:

No upstream notification.

No re-sign.

No upstream change to match, upstream should get option to pull the changes
upstream, or an to fork the record (new function I want). But, only when
next in the UX, and with no ability to overwrite the downstream record,
only to request downstream pull changes.

**Comment by prestonaustin** [comment]
Effectively this must be done before mid-august to be usable as intended in this round. However, sooner is better to fix some existing stuff.

**Comment by kellyhiser** [comment]
see: https://github.com/therabble/musicat-stem/issues/32
