### ISSUE TITLE
UX for librarians to open and close submissions

### ISSUE THREAD

**Issue by kellyhiser** [therabble/ca.epl.capitalcityrecords#232]

**Comment by prestonaustin** [comment]
- [ ] naming practice and process recommendation and constraints
 - [ ] possibly allow configuration of some display variables

**Comment by kellyhiser** [comment]
Everyone needs this, current target is Monday October 17 so that it's available for Nashville to open submissions on Tuesday October 18.

**Comment by kellyhiser** [comment]
see https://github.com/therabble/musicat-stem/issues/21
