### ISSUE TITLE
UX for editing notification emails

### ISSUE THREAD

**Issue by kellyhiser** [therabble/ca.epl.capitalcityrecords#234]
@acecarruthers can currently do this on github, so let's check in about best solution for this round and future.

**Comment by prestonaustin** [comment]
From 21 June call with @acecarruthers -> continued use of github is a good roadmap, and what we will do on this issue is clean that up, and be ready for multiple languages in the future, and 3rd support for EPL staff and a controlled process for this round.

**Comment by prestonaustin** [comment]
- [ ] Add album name variable where appropriate
 - [ ] Document which variables are available in what contexts and basics of how that works

**Comment by kellyhiser** [comment]
see https://github.com/therabble/musicat-stem/issues/24
