### ISSUE TITLE
Replace "New artists! New albums!" carousel image, link and text with Podcast promotion

### ISSUE THREAD

**Issue by raqmann** [therabble/ca.epl.capitalcityrecords#248]
Hello team, thank you in advance and please bare with me as this is my first experience on Github...

**Text:** 
Can you please replace the text that says:

New artists! New albums
New Edmonton music to stream and download for free
Listen

TO:

Capital City Records and CKUA have teamed up!
Check out our new podcast, “Song of the Week”
Subscribe

**Link**
Please have this banner link to: [http://capitalcityrecords.libsyn.com/](url)

**Image**
Please replace the current image with the one attached below:

![ccr_songoftheweek_ccrsitecarousel_870x400_nov2016_v5 2](https://cloud.githubusercontent.com/assets/23268939/20121796/9c137b26-a5d0-11e6-9028-50d7ceb81ab0.png)

**Comment by kellyhiser** [comment]
excellent first issue, @raqmann :)

@prestonaustin or @whblondeau is it okay to make these changes in CCR namespace as it is? I'm not sure of state of review there. If so, I'll show @raqmann how to do it.

**Comment by prestonaustin** [comment]
I can't recall if this got addressed out of band, but yes please freely
update in the namespace as is. Changes saved as PRs are best. For graphics,
just replacing it outright is fine, but if you can do that as a PR too
that's great (I don't recall if that option exists in the github web gui).
An issue pointing at a PR with a request for us to push it live, or a date
before/on/after which we can will help. Thanks :)
