### ISSUE TITLE
Add Videos Page Link

### ISSUE THREAD

**Issue by raqmann** [therabble/ca.epl.capitalcityrecords#250]
Hello team, 

We are ready to link the videos page to CCR. The link is: https://epl.capitalcityrecords.ca/

See #129 and #245 

In regards to the timeline, we are hoping as soon as possible, could this be something that is launched along with the upgrade on Nov. 29th?

We would need about one work week's notice so we can coordinate a social media campaign with Marketing along with our two partners. 

Thank you!

Best,
Raquel

**Comment by prestonaustin** [comment]
We can certainly include a link in the Nav bar to this (per #245) on
Tuesday 29 Nov. I probably can't add the video embed page (#129) with CMS
in a fully tested manner by then, but I could likely add that functionality
by the 6th without disrupting existing schedules much. I'll have to confirm
the latter with @kellyhiser on Monday 28 Nov.

**Comment by raqmann** [comment]
Sounds good! Thank you @prestonaustin
