### ISSUE TITLE
poster upload tool issue

### ISSUE THREAD

**Issue by lahollen** [therabble/ca.epl.capitalcityrecords#44]
http://submissions.capitalcityrecords.ca/submit/event-media 

When I selected “All posters are by the same artist” that artist name did not show up on the publishing page http://submissions.capitalcityrecords.ca/review-and-publish/posters and had to be manually entered again.  This has happened one time, but not every time.

**Comment by prestonaustin** [comment]
@acecarruthers - if you can provide more detail or info here as we proceed, please do. At this point we may have to leave this one hanging until we have more reports, as we have little to go on to target a fix.

**Comment by prestonaustin** [comment]
Moving to Post Launch but we way wish to reverse that if we get more info.

**Comment by kellyhiser** [comment]
we'll look at the entire tool when we add poster admin to current MUSICat
