### ISSUE TITLE
Mechanism and process to replace album's tracks, other assets

### ISSUE THREAD

**Issue by prestonaustin** [therabble/ca.epl.capitalcityrecords#45]
This needs further specification - @mbrakken feel free to add notes about this here.

**Comment by mbrakken** [comment]
Relates to #25. I think mostly we need clarity of what's supposed to happen here, given licenses, exposure, etc.

What should be the process when a librarian changes licensed media after a license has been signed? Once that's established, we can figure out how it fits in, or doesn't, with the current publishing workflow.

**Comment by prestonaustin** [comment]
We'll add an administrative capability for librarians to replace the assets
from artists and a note there stating one must:

"Use a version of the licensed asset, not an alternative image or track, to
ensure compliance with artist license terms."

And then maybe a notification to artist, but only after the capability
works and is tested as it's quite reasonable to swap covered assets within
the license terms as needed technically or aesthetically.

**Comment by mbrakken** [comment]
Err, I should have related this to #92, although #25 is relevant in it's own way.
