### ISSUE TITLE
Feature request: suppress options to purchase display when empty

### ISSUE THREAD

**Issue by lahollen** [therabble/ca.epl.capitalcityrecords#46]
Is it possible to only show the "Options to Purchase" toggle if there is content to display? I think that in almost all cases we received a link to Bandcamp so I don't think there will be too many instances where there is nothing to show.

**Comment by prestonaustin** [comment]
@nagapampa can you look at this one and see if it is easy, and if so assign this ticket to yourself and into Production Ready and do it when you get to it. Otherwise, just note what needs doing and leave it with me in Post Launch.
