### ISSUE TITLE
Artists, Albums, and Tracks export

### ISSUE THREAD

**Issue by prestonaustin** [therabble/ca.epl.capitalcityrecords#47]
- [x] Decide on a format for a list of everything that is published suitable for easy use in documents and relatively easily parsed (probably plaintext, RTF, or CSV, but not HTML or JSON)
      CSV is the decision - for first cut at this we will pull Artist name, Album name, Track Number, Track Name, Track Duration for every published track as a CSV
- [x] Confirm format with @acecarruthers
- [ ] Build an endpoint or an Ember UI for exporting list of everything that is published

**Comment by acecarruthers** [comment]
@prestonaustin let's go with CSV

**Comment by acecarruthers** [comment]
@prestonaustin I spoke with CSI this morning and they no longer require us to send them a full track list. I think this can be moved to a post-launch priority.

**Comment by prestonaustin** [comment]
I'm unassigning this until Production Ready stuff is done, then we can revisit its priority and spec. Unclear to me that this doesn't change since it's not needed for CSI/SOCAN anymore.

**Comment by acecarruthers** [comment]
CSI has contacted me and requested a complete track list including track name, track artists and song writer/publisher information. I believe that record label information can stand in for song writer/publisher information where ever we have it. Otherwise we'll have to put unavailable.

**Comment by acecarruthers** [comment]
Deadline for this is the morning of Thursday Aug 27

Email this to me in CSV or XLS format

**Comment by nagapampa** [comment]
@acecarruthers Please see the attached data export CSV.  I also attached a screenshot on where you can go to download the latest data and re-run the report.

![dataexportbutton](https://cloud.githubusercontent.com/assets/2964839/9513034/12767c5e-4c50-11e5-9e33-30a8e3bf5ae3.png)

**Comment by nagapampa** [comment]
I will email you the CSV... GIT will not let me attach it to the comments

**Comment by nagapampa** [comment]
@acecarruthers Please review the CSV I have sent via email.  I will be available tomorrow morning for any changes you would like me to make.

**Comment by acecarruthers** [comment]
@nagapampa thanks for this! Everything looks good except an o with an umlaut character is not resolving correctly for Zonik Records - the publisher of the  Wilfred N & the Grown Men album. 

![2015-08-27 10_15_58-microsoft excel - dataexport read-only](https://cloud.githubusercontent.com/assets/7355887/9526105/b1cb4362-4ca4-11e5-9bbd-3320fc294f3d.png)

In the short term I can just replace them in the file you sent me and send it off to CSI.

**Comment by mbrakken** [comment]
encoding... :(
