### ISSUE TITLE
Design requests: text bolding or resizing

### ISSUE THREAD

**Issue by lahollen** [therabble/ca.epl.capitalcityrecords#48]
- [ ] Individual album page: I’d be interested in seeing what the text looks like if everything is bolded – including the text in the player
- [ ] About Page / FAQ page: The small grey text contrasted against the very large headings makes this hard to read. (Same issue for FAQ page) Could the text be bolded and/or larger? 
- [ ] Playbar. Text is very small and a little hard to read. Could it be bold and/or a little larger?

**Comment by prestonaustin** [comment]
@acecarruthers Moving into Post Launch for consideration with other issues there together.

**Comment by kellyhiser** [comment]
closing for now, as this will all get swept up in CSS redesign after rewrite at some point.
