### ISSUE TITLE
Design request: change placement of tags on individual artist page

### ISSUE THREAD

**Issue by lahollen** [therabble/ca.epl.capitalcityrecords#49]
Could you experiment with other places for the tags? Their function is to be searchable keywords and to give people a sense of what they can expect from the music. Maybe put them closer to the album link?

**Comment by prestonaustin** [comment]
@acecarruthers this fell off my plate, I've swept it into Post Launch for now, and we can and should consider this and all other "might be nice(r) if" stuff as a set and prioritize after we are in production.

**Comment by kellyhiser** [comment]
i'm not sure what "tags" are referenced here. closing.
