### ISSUE TITLE
Show More button not revealing more text

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ca.epl.capitalcityrecords#93]
Clicking "Show More" on the last three artist pages I visited resulted in a strange glitch. Screenshot below from https://wax.capitalcityrecords.ca/artists/death-by-robot

![showmore_7272015](https://cloud.githubusercontent.com/assets/7355887/8914168/f5560c78-345a-11e5-9f96-7c0baca42ec4.jpg)

The "Show More" text disappears, but the rest of the artist bio does not appear. When I click anywhere on the screen other than in between the faint grey bars, the "Show Less" text appears between the grey bars. When I click "Show Less", nothing happens except the text disappears. 

This has happened so far on:
F & M https://wax.capitalcityrecords.ca/artists/f-and-m
Choir and Marching Band https://wax.capitalcityrecords.ca/artists/choir-and-marching-band
and Death by Robot. 

Alex, Desktop, Firefox 39, 27 July, 12:30pm MT

**Comment by mbrakken** [comment]
We have a series of strange, intermittent issues like this one. See also #91,#57, #34, and some other artifacts I can't track down issues for. My leading guess is that this remains related to memory issues, so we may need to look for memory leaks. There was a memory leak in ember's glimmer rendering engine that was recently closed off, so we may need to update from 1.13.0 to 1.13.5 (glimmer was introduced with 1.13.0).

We may want to look for any leaks internal to the app code, too, possibly around lingering media references (tracks and images) that could block garbage collection.

Knowing if these types of issues crop up after a long, active session, and go away on a hard refresh, would likely indicate a memory issue.

**Comment by prestonaustin** [comment]
@acecarruthers See Marc's last sentence above, any sense of how far into
using the app these things are happening for testers?

**Comment by acecarruthers** [comment]
I had been on the site for probably three hours before I noticed. I didn't try to click "See More" until around three hours.

**Comment by prestonaustin** [comment]
Marc is probably right then, we are likely evading garbage collection
somewhere. @acarruthers, did the site (or your computer) seem to get less
responsive to clicks over time?

**Comment by acecarruthers** [comment]
Not that I noticed.

**Comment by prestonaustin** [comment]
@acecarruthers I'm going to leave this on the milestone, but we'll probably end up punting on it and gathering data over time to close out the problems that cause this sort of thing. An inelegant but effective fix to these issues may be to occasionally dump state and reload the whole ember app from browser cache, but we can't do that while music is playing or a download in progress, for example.

**Comment by kellyhiser** [comment]
this works now.
