### ISSUE TITLE
Larger Player Buttons for small mobile screens

### ISSUE THREAD

**Issue by prestonaustin** [therabble/ca.epl.capitalcityrecords#95]
Player buttons are too small and some finding them hard to use.
@acecarruthers could you provide screenshots if you have them from some small devices and mark up your thoughts on how big you would like things? We'll propose a design I just want a sense of what you are thinking from the feedback you received.

**Comment by acecarruthers** [comment]
Is something like this possible? The buttons in the playbar are maybe twice as big and proportionally farther apart. Pushing the album title and song title over to the side could cause problems with very long titles. I chose the longest album title we have as an example of how we could maybe shorten the titles so everything important is visible. I didn't change the height of the playbar at all. 

![playbardesign](https://cloud.githubusercontent.com/assets/7355887/8916893/d0fe621a-346b-11e5-912b-617d5387c8d6.png)

**Comment by acecarruthers** [comment]
or maybe something like this? The pause/play button is three times bigger here. This could probably be refined to be prettier, but you get the idea. 

![playbardesign2](https://cloud.githubusercontent.com/assets/7355887/8917115/65da5442-346d-11e5-93fc-ba197aad480a.png)

**Comment by prestonaustin** [comment]
@acecarruthers Thanks, that gives me clarity on what you were looking for here. We'll probably go with something like your first option, and we'll put together a design you can approve before that. I would like to take this off Production Ready as it is from a purely technical perspective a non-blocking UX, just something we want to improve, unless you consider the current UX as visitor-blocking from an usability perspective.

**Comment by kellyhiser** [comment]
Issue moved to [therabble/musicat-stem #97](https://github.com/therabble/musicat-stem/issues/97) via [**ZenHub**](https://www.zenhub.com/)
